spring.datasource.url=jdbc:postgresql://localhost:5432/praxis
spring.datasource.username=praxis
spring.datasource.password=praxis
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false